# Generated by Django 2.2.1 on 2019-05-21 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_profile_favorite_articles'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favorite_profiles', models.ManyToManyField(blank=True, to='blog.Profile')),
            ],
        ),
    ]
