# Generated by Django 2.2.1 on 2019-05-22 21:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0007_favorite'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_profiles',
            field=models.ManyToManyField(blank=True, related_name='fav_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
