# Generated by Django 2.2.1 on 2019-05-23 00:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0008_auto_20190523_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, related_name='user_reaction', to=settings.AUTH_USER_MODEL),
        ),
    ]
