# Generated by Django 2.2.1 on 2019-05-23 00:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0009_post_users_reaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='users_reaction',
            field=models.ManyToManyField(blank=True, related_name='user_reaction_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
